from app.routers import agents as agents_router  # noqa: F401
from app.routers import benchmark as benchmark_router  # noqa: F401
from app.routers import conversations as conversations_router  # noqa: F401
from app.routers import cron as cron_router  # noqa: F401
from app.routers import mcp as mcp_router  # noqa: F401
from app.routers import prompt as prompt_router  # noqa: F401
from app.routers import quality as quality_router  # noqa: F401
from app.routers import sandbox as sandbox_router  # noqa: F401
from app.routers import settings as settings_router  # noqa: F401
from app.routers import speech as speech_router  # noqa: F401
from app.routers import uploads as uploads_router  # noqa: F401
from app.routers import webhook as webhook_router  # noqa: F401
from app.routers import workflows as workflows_router  # noqa: F401
